#!/bin/sh

SENSOR_CMD='./sensors/cpu-all-cores' # use evl for advanced expressions ('evl "$(./sensors/cpu-all-cores) + 5"')

#FAN_CURVE='<temperature>=<speed> ...' points that will be linearly interpolated
FAN_CURVE='
0=10
25=20
60=70
70=100
'