#!/bin/sh

set -e

INTERVAL=${1:-3}

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$(readlink -f "$0")")" && pwd)
export SCRIPT_DIR

AWK=$(command -v awk)
export AWK

CACHE_DIR=/run/fanctrl/fans
mkdir -p "$CACHE_DIR"
export CACHE_DIR

ENABLE_MANUAL=$(cat "$SCRIPT_DIR/commands/enable-manual-fan-ctrl")
FANCTRL="$SCRIPT_DIR/fanctrl"

cleanup()
{
	rm -rf "$CACHE_DIR"
	sh -c "$ENABLE_MANUAL" _ 0
}

trap cleanup EXIT
trap 'exit 1' HUP INT TERM QUIT

eval "$ENABLE_MANUAL"

while :
do
	sh "$FANCTRL"
	sleep "$INTERVAL"
done

cleanup
