#!/bin/sh

INTERVAL=${1:-3}

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$(readlink -f "$0")")" && pwd)

ENABLE_MANUAL="$SCRIPT_DIR/commands/enable_manual_fan_ctrl"
FANCTRL="$SCRIPT_DIR/fanctrl"

run=1

cleanup()
{
	"$ENABLE_MANUAL" 0
	run=0
}

trap cleanup EXIT HUP INT TERM QUIT

"$ENABLE_MANUAL" 1 || exit 1

while [ "$run" -eq 1 ]; do
	sh "$FANCTRL"
	stts=$?

	if [ "$stts" -ne 0 ]; then
		cleanup
		exit "$stts"
	fi

	sleep "$INTERVAL"
done

cleanup
